---
kube_cidr: 192.168.33.0/24
kube_version: 1.19.7
kube_vversion: v{{kube_version}}
kubelet_version: "{{kube_version}}-00"
kubeadm_version: "{{kube_version}}-00"
kubectl_version: "{{kube_version}}-00"
advertiseAddress: "{{ ansible_all_ipv4_addresses | ansible.netcommon.ipaddr(kube_cidr) | first }}"
clusterName: tiredanimal
kernel_modules:
  - br_netfilter
  - overlay

pod_network_cidr: 10.244.0.0/16
