---
resources:
  - ../../base/tigera-operator
  - ../../base/metallb
  - ../../base/csi-driver-nfs
  - ../../base/longhorn/v1.1.0
  - ./storageclasses.yaml
  # - ../../base/postgresql/zalando-v1.6.1
  # - postgresql/config.yaml
