---
resources:
  - ../../base/tigera-operator
  - ../../base/metallb
  - ../../base/csi-driver-nfs
  - ../../base/longhorn/v1.1.0
  - ../../base/metrics-server/v0.3.7
  - ./storageclasses.yaml
  - ../../base/podinfo/v5.2.1
  
  # - ../../base/postgresql/zalando-v1.6.1
  # - postgresql/config.yaml

patches:
  - path: patch-podinfo.yaml
  - path: patch-metrics-server.yaml
