---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: postgres
    volumeAttributes:
      server: 192.168.50.254
      share: /volume1/k8s_pv/postgres

