version: 1
config:
  - type: physical
    name: ens3
    subnets:
      - type: static
        address: ${network_addr}
        gateway: ${gateway_ip}
  - type: nameserver
    address:
      - ${nameserver_ip}
