#cloud-config
# vim: syntax=yaml
ssh_pwauth: True
chpasswd:
  list:
    - 'root:root'
  expire: False

ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDy6EgOgmiyjhTQqVNDmqVF1u0ahvQUOf1zvgGaIDRMk matt@manjaro

packages:
  - qemu-guest-agent

runcmd:
  - rm /etc/udev/rules.d/75-cloud-ifupdown.rules

power_state:
  mode: reboot
