---
- name: Add Docker APT signing key
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Get DEB architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install containerd
  ansible.builtin.apt:
    name:
      - containerd.io
    update_cache: yes

- name: containerd config
  ansible.builtin.copy:
    src: containerd_config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart containerd
