---
- name: Configurer kernel parameters
  ansible.builtin.include_tasks: kernel.yaml

- name: Generate /etc/hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"

- name: Install required software packages
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gpg
      - open-iscsi
    update_cache: yes

- name: Install containerd
  ansible.builtin.include_tasks: containerd.yaml

- name: Install Kubernetes tools
  ansible.builtin.include_tasks: kubetools.yaml

- name: Configure calico
  ansible.builtin.include_tasks: calico.yaml
